### ISSUE TITLE
[*] DateOnly - Sequelize 4 returns date strings not timestamps so don't shift

### ISSUE THREAD

**Issue by gcoombe** [ForestAdmin/forest-express-sequelize#159] opened 2018-01-18 00:32 UTC
As of Sequelize 4 dateonly fields are returned as date strings not
dateTime strings. Therefore the formatting functionality here will
return incorrect values for dateonly fields in Sequelize 4 if the server
is in a timezone with a negative UTC shift.

Ex: I have 1990-10-02 stored in my DB. The formatting function will
shift that to 1990-10-01T16:00:00 if I am in PST. In the UI 01/10/1990
will be shown

https://github.com/sequelize/sequelize/issues/4858

I made a pull request for this #153 but forgot to make an issue.  

Please also take a look at https://github.com/ForestAdmin/forest-express/pull/123 where this also needed to be fixed

**Comment by arnaudbesnier** [comment] 2018-05-25 13:41
Hi @gcoombe, I cannot reproduce your issue in my postgresql/sequelize4 environment with a `date` type.
```javascript
fieldDateOnly: { type: DataTypes.DATEONLY },
```

Could you share with us your database type, the column type you have configured and the field declaration in Sequelize.

**Comment by arnaudbesnier** [comment] 2018-06-08 14:43
Hi @gcoombe, can you please help?

**Comment by gcoombe** [comment] 2018-06-11 00:07
Hi @arnaudbesnier apologies for the delay. The noted fix version seem to fix the problems on my end. I can still repro the issue on master.  My set up is as follows: 
- column type: : DataTypes.DATEONLY
- db: postgres
- sequelize version:  4.37.1

Your server must be in a location with a negative UTC shift to repro.

**Comment by arnaudbesnier** [comment] 2018-06-11 05:22
Thanks @gcoombe, I think you missed the most important part of the response, which is the column type defined in your Postgres database. ;)

I tried to reproduce the issue with the exact same conditions, so I guess the difference we have is the column type.

**Comment by gcoombe** [comment] 2018-06-11 15:27
Hi @arnaudbesnier the column type was date

**Comment by arnaudbesnier** [comment] 2018-06-17 18:19
Hi @gcoombe, the fix has been released in Forest v2.12.1.

Thanks for the feedback.

🌲🌲🌲

**Closed by arnaudbesnier** 2018-06-17 18:19 UTC
Labels: bug
