### ISSUE TITLE
Validation error on JSONB fields with defaultValue

### ISSUE THREAD

**Issue by saimeunt** [ForestAdmin/forest-express-sequelize#186] opened 2018-05-18 09:30 UTC
## Expected behavior

When using a JSONB field it should not trigger a "can't be blank" error on validation.

## Actual behavior

Error when submitting the edition form.

## Failure Logs

[https://ibb.co/fySeiy](https://ibb.co/fySeiy)

## Context

```
deck: {
    type: Sequelize.JSONB,
    defaultValue: [],
    allowNull: false,
},
```

* Package Version: 2.8.6
* Express Version: 4.16.3
* Sequelize Version: 4.37.7
* Database Dialect: PostgreSQL
* Database Version: 9.6.6

**Comment by arnaudbesnier** [comment] 2018-06-18 09:00
Hey @saimeunt! I just made a fix on Forest client about JSON fields validation.
The patch has just been released in production.

Can you refresh your Forest page, test it again and validate that the issue is fixed?

Thanks for your feedback!!!

🌲🌲🌲

**Comment by saimeunt** [comment] 2018-06-18 12:32
It works now as intended! 👍

**Closed** 2018-06-18 12:36 UTC
Labels: bug
